### ISSUE TITLE
fasterq-dump crashes for all SRA accessions

### ISSUE THREAD

**Issue by mmp3** [ncbi/sra-tools#464]
Last week, this command completed successfully:

`fasterq-dump  SRR341578`

This week, it fails with error message:

```
$ fasterq-dump  SRR341578
2021-02-02T13:28:57 fasterq-dump.2.10.8 err: transfer incomplete while reading file within network system module - error with https open 'https://locate.ncbi.nlm.nih.gov/sdlr/sdlr.fcgi?jwt=eyJhbGciOiJSUzI1NiIsImtpZCI6InNkbGtpZDEiLCJ0eXAiOiJKV1QifQ.eyJleHAiOjE2MTIyNzYxMzcsImlhdCI6MTYxMjI3MjUzNywibGluayI6Imh0dHBzOi8vc3JhLXB1Yi1ydW4tNS5zMy5hbWF6b25hd3MuY29tL1NSUjM0MTU3OC9TUlIzNDE1NzguMT9uY2JpX3BoaWQ9QTNDMzFDODUzMDBCNjEzNTAwMDAzMjMyNzJGM0JBQzkuMS4xJngtYW16LXJlcXVlc3QtcGF5ZXI9cmVxdWVzdGVyIiwicmVnaW9uIjoidXMtZWFzdC0xIiwic2VydmljZSI6InMzIiwic2lnbmluZ0FjY291bnQiOiJzcmFfczMiLCJ0aW1lb3V0Ijo2MDAwfQ.DQ8hh2vjUluw8ZNytbwqSfWBZZ_DDJnFz6viGUpfKqAt0AaUcjAEhd6CFEaeA-GCmIIg8W6pFOHUk4QEXqaFAFnmksphnrDsrQ4F7dWKj4EUG47PoP769i3IEQi4PgZFREZ4YMO35ZmHHogNZHTL3Ia99bUI5ZcPae6jGAKZl_JdiSWipnkcVC1UHLkKHldvwhTKK0ra8GMc7maqcMPo2aBo0EBLVVZ8h3ICw54nzAJpCxsYHCLEdAoWWcxF759eJYAvt7GeJHnGMzIGY3iYAnnyInf4KyFZZgzxS0XYm07K4urgJlvOR_7Pnbm3fc8Mt1ezVHUgljcMAJsrvqFHsw'
2021-02-02T13:28:57 fasterq-dump.2.10.8 err: invalid accession 'SRR341578'
```

Note that `SRR341578` is used as an example to demonstrate the usage of `fasterq-dump` in the [fasterq-dump documentation page](https://github.com/ncbi/sra-tools/wiki/HowTo:-fasterq-dump).

In fact, I get the same error message for _every_ SRA accession that I try.

**Comment by marisalim** [comment]
Hi, I got the same kind of error as above, where this `fasterq-dump` command worked fine a few weeks ago:
```
fasterq-dump SRR5368359 -O ./
```
Error:
```
2021-02-03T03:37:29 fasterq-dump.2.10.9 err: empty while validating file within network system module - error with https open 'http
s://locate.ncbi.nlm.nih.gov/sdlr/sdlr.fcgi?jwt=eyJhbGciOiJSUzI1NiIsImtpZCI6InNkbGtpZDEiLCJ0eXAiOiJKV1QifQ.eyJleHAiOjE2MTIzMjcwNDYsI
mlhdCI6MTYxMjMyMzQ0NiwibGluayI6Imh0dHBzOi8vc3RvcmFnZS5nb29nbGVhcGlzLmNvbS9zcmEtcHViLXJ1bi0yL1NSUjUzNjgzNTkvU1JSNTM2ODM1OS4xIiwicmVn
aW9uIjoidXMiLCJzZXJ2aWNlIjoiZ3MiLCJzaWduaW5nQWNjb3VudCI6InNyYV9ncyIsInRpbWVvdXQiOjYwMDB9.n5Sng6-tipTgenlakhP08Z0iH_yhkzsxogXyYrsFRi
2gV8Zh_s1uF9G-j3fi6B4vzolMm6PArcdGlCCpERddspbBisO4xKp2GuKL-VzKo8Rvzleb9FKJ_WqJTpJGaaYihCxNfV01TxHOFn0R21EQMXTc7k_mxjkOSiRShU-h17L4O
4PFLELbE4Gxer6nvw5EGJedPMD9wm3SHEzVaT2UGjZ8fBe0XAHnp0t6F_DuLOa5MVN7NT8ywFvuwwZIzQOtOkGWkRznhtvbQG0Iz1RpbrU3HdMMUUFofWN9V943Z5wnvZu0
CcY8h5kEIF1SNEqVs2dzd2yLV4S0RyIO59_BIA&ncbi_phid=D0BD33313654F45500002D618EFBEFBF.1.1'
2021-02-03T03:37:29 fasterq-dump.2.10.9 err: invalid accession 'SRR5368359'
```
I'm running SRA toolkit version 2.10.9 from a Google Cloud VM. Would appreciate any pointers!

**Comment by samkleeman1** [comment]
Same problem!!!

**Comment by klymenko** [comment]
Messages like ```...2.10.9 err: empty while validating file within network system module - error with https open 'http
s://locate.ncbi.nlm.nih.gov/sdlr/sdlr.fcgi...``` were cased by failure of NCBI data locator service that should be fixed now.
Please retry.

If you encounter failures in `network system module` - run `prefetch` first, and then, run `fasterq-dump`:
https://github.com/ncbi/sra-tools/wiki/08.-prefetch-and-fasterq-dump

**Comment by samkleeman1** [comment]
Many thanks for the update. I have had massive issues with this toolkit over the last couple of months with continuous errors of this nature, that were not resolved by prefetch. In fact prefetch often makes things worse as when it fails it leaves an empty folder, that fasterq-dump then tries to use to extract FASTQ files, then failing in turn.

**Comment by samkleeman1** [comment]
Still seeing same error as of right now
```
2021-02-09T17:38:07 fasterq-dump.2.10.9 err: empty while validating file within network system module - error with https open 'https://gap-download.be-md.ncbi.nlm.nih.gov/sragap/04AB577A-584A-4E9E-9D4F-A6B1D7920C37/SRR2648104'
2021-02-09T17:38:07 fasterq-dump.2.10.9 err: invalid accession 'SRR2648104'
```

**Comment by mmp3** [comment]
@klymenko 
`prefetch` throws the same error:

```
2021-02-11T17:16:31 prefetch.2.10.8 int: empty while validating file within network system module - cannot open remote file: https://locate.ncbi.nlm.nih.gov/sdlr/sdlr.fcgi?jwt=eyJhbGciOiJSUzI1NiIsImtpZCI6InNkbGtpZDEiLCJ0eXAiOiJKV1QifQ.eyJleHAiOjE2MTMwNjczOTAsImlhdCI6MTYxMzA2Mzc5MCwibGluayI6Imh0dHBzOi8vc3JhLXB1Yi1ydW4tNi5zMy5hbWF6b25hd3MuY29tL1NSUjg5Mjg5NjgvU1JSODkyODk2OC4xP25jYmlfcGhpZD00MjU0MEUxNkVERkVGQzE1MDAwMDJCREYwOENEMTg5Ny4xLjEmeC1hbXotcmVxdWVzdC1wYXllcj1yZXF1ZXN0ZXIiLCJyZWdpb24iOiJ1cy1lYXN0LTEiLCJzZXJ2aWNlIjoiczMiLCJzaWduaW5nQWNjb3VudCI6InNyYV9zMyIsInRpbWVvdXQiOjYwMDB9.PAaUsd2B-JfDg-09GWV9tS8F7MeoFJQJYoBun-l1fndMPOuCxtEnzFUGTMhIcakbyWzXIqrcip8vSwk-S1uIpqlMmE_HFM5-EoX6FHW3QrM2Lr2jVsqX2XwExGmqL177uTtF1HJ_RlDwby4eWkzTm8bivW4RthSneUCXg5mPPm6PSpnPd4miWXnB4bxbNGa7j8RqLG0moKjpCLtLMwXMoe_9V1V1V0sptQZnKszYGVH7LTxkmkG6Aw8TMI2hwhKkk7o9FyWCGQjCB5i1RWMAWipsTxIH4fGHlrTgBe1cJ3wmrtRREhx06X37LdVASB3tPecZB5T3_Ekp1iUEYCwA3Q
2021-02-11T17:16:31 prefetch.2.10.8: 1) Downloading 'SRR8928968'...
2021-02-11T17:16:31 prefetch.2.10.8:  Downloading via HTTPS...
2021-02-11T17:16:31 prefetch.2.10.8 int: self NULL while reading file within network system module - Cannot KStreamRead: /data1/scratch/salmon/out/PRJNA533627/salmon_output/SRS4649084/input_fastqs/SRR8928968.sra

```

**Comment by klymenko** [comment]
If `prefetch` fails - run it again. It will resume.
Add `-p` option to see progress.

**Comment by samkleeman1** [comment]
There are major ongoing issues with this toolkit, can you advise me regarding someone I can email to escalate this issue?

**Comment by klymenko** [comment]
@samkleeman1, did you run `prefetch`?

**Comment by klymenko** [comment]
@samkleeman1 , @mmp3 , do you still need help?

**Comment by erhoppe** [comment]
I'm getting the same "fasterq-dump.2.10.9 err: invalid accession" error. It began after killing a few test runs (that ran successfully) and I can run the commands (e.g. "fasterq-dump --progress SRR315297") successfully on a different node in our system (screenshot attached; left one run after right one failed again). I grabbed a huge node so I'd prefer to use the one that's currently failing...is there some sort of anti-DDos system running that might be interpreting a few identical requests from the same server as problematic and be blocking all future attempts? Something else? 
[fasterq-dump_error.pdf](https://github.com/ncbi/sra-tools/files/6152659/fasterq-dump_error.pdf)

**Comment by mmp3** [comment]
@klymenko 
I updated to 2.10.9 as you indicated and the error persists.
If I put `prefetch` in a while loop, then it will eventually complete successfully, often after > 20 failed attempts first.

**Comment by samkleeman1** [comment]
I can confirm the issue is ongoing and I agree with @erhoppe that this appears to be a DDOS-type problem. It caused me real issues, taking as much as a month to download our dataset. I found that it is particularly problematic when you have already downloaded some files and you restart the download, the multiple requests to check files' checksum (presumably) causes the DDOS-type firewall to activate.

**Comment by erhoppe** [comment]
@mmp3 and @samkleeman1 , are you able to downgrade to 2.9? We had the module for 2.9.2 built on our node system and it's working well for me. I know that others in our lab are using 2.9.4 successfully, as well. The issues seem to start cropping up (based on other similar issue reports here and elsewhere) around the release of 2.10, so you might downgrade in the meantime until whatever causing this issue is fixed. This would seem to counteract my DDoS hypothesis, unless they fundamentally changed how the handshake occurs between versions, but whatever works, eh?

**Comment by klymenko** [comment]
We are looking into this issue.

FYI:
When a file is available from both NCBI and AWS - prefetch.2.9 version will always get it from NCBI.

In this case changing 'report cloud instance identity' checkbox in vdb-config when using the recent toolkit will allow to get from NCBI - if unchecked, from cloud - if checked.

**Comment by klymenko** [comment]
Do you still have this issue?
